VideoGameLibrary/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace VideoGameLibrary.Areas.Admin.Controllers
{
    public class HomeController : BaseAdminController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

VideoGameLibrary/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using VideoGameLibrary.Services.Data.Interfaces;
using VideoGameLibrary.Web.ViewModels.User;

namespace VideoGameLibrary.Areas.Admin.Controllers
{
	using static Common.GeneralApplicationConstants;
	public class UserController : BaseAdminController
    {
        private readonly IUserService userService;
        private readonly IMemoryCache memoryCache;

        public UserController(IUserService userService, IMemoryCache memoryCache)
        {
            this.userService = userService;
            this.memoryCache = memoryCache;
        }
        [Route("User/All")]
        [ResponseCache(Duration = 30, Location = ResponseCacheLocation.Client, NoStore = false)]
        public async Task<IActionResult> All()
        {
            IEnumerable<UserViewModel> users =
                memoryCache.Get<IEnumerable<UserViewModel>>(UsersCacheKey);
            if (users == null)
            {
                users = await userService.AllAsync();

                MemoryCacheEntryOptions cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan
                        .FromMinutes(UsersCacheDurationMinutes));

                memoryCache.Set(UsersCacheKey, users, cacheOptions);
            }

            return View(users);

        }
    }
}

VideoGameLibrary/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using static VideoGameLibrary.Common.GeneralApplicationConstants;

namespace VideoGameLibrary.Controllers
{

	public class HomeController : Controller
    {
        public IActionResult Index()
        {
            if (User.IsInRole(AdminRoleName))
            {
                return this.RedirectToAction("Index", "Home", new { Area = AdminAreaName });
            }
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(int statusCode)
        {
            if (statusCode == 400 || statusCode == 404)
            {
                return View("Error404");
            }

            if (statusCode == 401)
            {
                return View("Error401");
            }

            return View();
        }
    }
}

VideoGameLibrary/Controllers/ModeratorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VideoGameLibrary.Services.Data.Interfaces;
using VideoGameLibrary.Web.Infrastructure.Extensions;
using VideoGameLibrary.Web.ViewModels.Moderator;


namespace VideoGameLibrary.Controllers
{
	using static VideoGameLibrary.Common.NotificationMessagesConstants;


	[Authorize]
	public class ModeratorController : Controller
	{
		private readonly IModeratorService moderatorService;
		private readonly IUserService userService;

		public ModeratorController(IModeratorService moderatorService, IUserService userService)
		{
			this.moderatorService = moderatorService;
			this.userService = userService;
		}

		[HttpGet]
		public async Task<IActionResult> Become()
		{
			string? userId = User.GetId();
			bool isModerator = await moderatorService.ModeratorExistsByUserIdAsync(userId!);
			if (isModerator)
			{
				TempData[ErrorMessage] = "You're a moderator already!";

				return RedirectToAction("All", "Game");
			}

			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Become(ModeratorApplicationViewModel model)
		{
			string? userId = User.GetId();

			bool isModerator = await moderatorService.ModeratorExistsByUserIdAsync(userId!);
			if (isModerator)
			{
				TempData[ErrorMessage] = "You're a moderator already!";

				return RedirectToAction("All", "Game");
			}

			bool isPhoneNumberTaken =
				await moderatorService.ModeratorExistsByPhoneNumberAsync(model.PhoneNumber);
			if (isPhoneNumberTaken)
			{
				ModelState.AddModelError(nameof(model.PhoneNumber), "Moderator with the provided phone number already exists!");
			}

			if (!ModelState.IsValid)
			{
				var errors = ModelState
					.Where(x => x.Value.Errors.Count > 0)
					.Select(x => new { x.Key, x.Value.Errors })
				.ToArray();

				return View(model);
			}

			try
			{
				await moderatorService.Submit(userId!, model);
				TempData[SuccessMessage] = "You've successfully applied to be a moderator!";
			}
			catch (Exception)
			{
				TempData[ErrorMessage] =
					"Unexpected error occurred while trying to submit your form to become a moderator. Please try again later!";
				return View(model);
			}

			return RedirectToAction("All", "Game");
		}

		[HttpGet]
		public async Task<IActionResult> OptOut()
		{
			string userId = User.GetId()!;
			bool isModerator = await moderatorService.ModeratorExistsByUserIdAsync(userId!);

			if (!isModerator)
			{
				TempData[ErrorMessage] = "You need to be a moderator!";

				return RedirectToAction("All", "Game");
			}

			string moderatorId = await moderatorService.GetModeratorIdByUserIdAsync(userId);

			if (string.IsNullOrEmpty(moderatorId))
			{
				TempData[ErrorMessage] = "Moderator does not exist!";

				return RedirectToAction("All", "Game");
			}

			try
			{
				ModeratorOptOutViewModel model = await moderatorService
					.GetViewForOptingOut(moderatorId);
				
				return View(model);
			}
			catch (Exception)
			{
				return GeneralError();
			}

		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Remove()
		{
			string userId = User.GetId()!;
			bool isModerator = await moderatorService.ModeratorExistsByUserIdAsync(userId!);

			if (!isModerator)
			{
				TempData[ErrorMessage] = "You need to be a moderator!";

				return RedirectToAction("All", "Game");
			}

			string moderatorId = await moderatorService.GetModeratorIdByUserIdAsync(userId);

			if (string.IsNullOrEmpty(moderatorId))
			{
				TempData[ErrorMessage] = "Moderator does not exist!";

				return RedirectToAction("All", "Game");
			}

			try
			{
				await moderatorService.RemoveModeratorAsync(moderatorId);
				TempData[SuccessMessage] = "You successfully opted out of being a moderator!";
				return RedirectToAction("All", "Game");
			}
			catch (Exception)
			{
				return GeneralError();
			}

		}

		private IActionResult GeneralError()
		{
			TempData[ErrorMessage] =
				"Unexpected error occurred! Please try again later or contact administrator";

			return RedirectToAction("All", "Game");
		}
	}
}

VideoGameLibrary/Areas/Admin/Views/Home/Index.cshtml
<link rel="stylesheet" href="~/css/dark.css" asp-append-version="true" />

@{
	ViewData["Title"] = "Admin Dashboard";
}

<div class="container mt-4">
	<h2 class="text-center">Welcome to the Admin Dashboard</h2>
	<div class="row mt-4">
		<div class="col-md-6">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">Manage Moderators</h5>
					<p class="card-text text-dark">Manage moderators and their permissions.</p>
					<a asp-area="Admin" asp-controller="Moderator" asp-action="AllSubmissions" class="btn btn-primary">Go to Submissions</a>
					<a asp-area="Admin" asp-controller="Moderator" asp-action="AllModerators" class="btn btn-primary">All Moderators</a>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">View Users</h5>
					<p class="card-text text-dark">View all users in the library</p>
					<a asp-area="Admin" asp-controller="User" asp-action="All" class="btn btn-primary">Go to Users</a>
				</div>
			</div>
		</div>
	</div>

	<div class="row mt-4">
		<div class="col-md-6">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">Manage Games</h5>
					<p class="card-text text-dark">Manage deleted games</p>
					<a asp-area="Admin" asp-controller="Game" asp-action="DeletedGames" class="btn btn-primary">Go to Games</a>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">Manage Platforms</h5>
					<p class="card-text text-dark">Add, edit, and delete platforms in the library.</p>
					<a asp-area="" asp-controller="Platform" asp-action="PlatformCrud" class="btn btn-primary">Go to Games</a>
				</div>
			</div>
		</div>
	</div>

	<div class="row mt-4">
		<div class="col-md-6">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">Manage Genres</h5>
					<p class="card-text text-dark">Add, edit, and delete genres in the library.</p>
					<a asp-area="" asp-controller="Genre" asp-action="GenreCrud" class="btn btn-primary">Go to Games</a>
				</div>
			</div>
		</div>
	</div>
</div>